### ISSUE TITLE
Feature: Implement the F12 idea

### ISSUE THREAD

**Issue by gcarreno** [gcarreno/laz-JSON-Viewer#15]
- [x] Create a non visible panel to hide the `TSynEdit`
- [x] DO NOT FORGET THE READ-ONLY!! ;-D
- [x] Add an action to show/hide the panel
- [x] Upon completion don't forget to credit Craig (@chapmanworld)

**Comment by chapmanworld** [comment]
As it's a viewer only - smash that 'read-only' property :-)

**Comment by gcarreno** [comment]
Got it covered ;)

**Comment by gcarreno** [comment]
Hey Craig(@chapmanworld),

Okay, did the absolute minimum to get the `F12` working.

I now need to find/create a better syntax highlighter for the JSON, step one.
Step 2 is to match position of tree and JSON when toggling from one view to another. This is gonna be mad!!

Please tell me what you think of it as it is now.

Cheers,
Gus

**Comment by gcarreno** [comment]
Closed by bf14244
